name: smart_home_fe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  convex_bottom_bar: ^3.2.0
  dashed_line: ^0.1.0+3
  flutter:
    sdk: flutter
  flutter_iot_wifi: ^0.0.3
  font_awesome_flutter: ^10.7.0
  http: ^1.2.0
  permission_handler: ^11.3.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.2
  show_hide_password: ^0.0.2
  wifi_iot: ^0.3.19
  wifi_scan: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
